exclude = ["venv*"]
line-length = 99
lint.ignore = [
  "PLR2004",  # Magic value used in comparison, consider replacing {value} with a constant variable
  "D104",     # Missing docstring in public package
  "D107",     # Missing docstring in __init__
  "PT001",  # Use `@pytest.fixture()` over `@pytest.fixture`
  "PT023",  # Use `@pytest.mark.asyncio()` over `@pytest.mark.asyncio`
]
lint.select = [
    # "B",   # bandit
    "C",   # complexity
    "D",   # docstrings
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "I",   # isort
    "PT",  # flake8-pytest
    "RUF", # ruff base config
    "SIM", # flake-simplify
    "UP",  # pyupgrade
    "W",   # pycodestyle warnings
    "YTT", # flake8-2020
    "ARG", # flake8-unused args
]
[lint.pydocstyle]
convention = "pep257"
[lint.flake8-unused-arguments]
ignore-variadic-names = true
